/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestetudiant;

import com.sun.java.swing.plaf.windows.WindowsInternalFrameTitlePane;
import static gestetudiant.GestEtudiant.jTable1;
import static gestetudiant.GestScores.jTable1;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author SEIF
 */
public class AjouterScore extends javax.swing.JFrame {

    /**
     * Creates new form AjouterScore
     */
    Cours c= new Cours();
    Etudiant e=new Etudiant();
    public AjouterScore() {
        initComponents();
        Cours c=new Cours();
        c.chargerCoursCombo(jComboBox_id_cours);
           e.chargerEtudiants(jTable1, "");
           hideColumn(6);
           hideColumn(5);
           hideColumn(4);
           hideColumn(3);
            jTable1.setRowHeight(50);
 jTable1.setShowGrid(true);
 jTable1.setGridColor(Color.black);
 jTable1.setSelectionBackground(Color.blue);
    }
    private void hideColumn(int indx){
        TableColumn col=jTable1.getColumnModel().getColumn(indx);
        col.setMaxWidth(0);
        col.setMinWidth(0);
        col.setPreferredWidth(0);
               
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_idetd = new javax.swing.JTextField();
        jLabel_Nom1 = new javax.swing.JLabel();
        jLabel_Nom = new javax.swing.JLabel();
        jTextField_score = new javax.swing.JTextField();
        jButton_Annuler = new javax.swing.JButton();
        jButton_ajouter = new javax.swing.JButton();
        jLabel_Nom2 = new javax.swing.JLabel();
        jComboBox_id_cours = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_Nom3 = new javax.swing.JLabel();
        jTextField_description = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ajouter score");

        jTextField_idetd.setEditable(false);
        jTextField_idetd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_idetd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idetdActionPerformed(evt);
            }
        });

        jLabel_Nom1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom1.setText("Id Etudiant:");

        jLabel_Nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom.setText("Cours:");

        jTextField_score.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_scoreActionPerformed(evt);
            }
        });
        jTextField_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_scoreKeyTyped(evt);
            }
        });

        jButton_Annuler.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/error.png"))); // NOI18N
        jButton_Annuler.setText("Annuler");
        jButton_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnnulerActionPerformed(evt);
            }
        });

        jButton_ajouter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton_ajouter.setText("Ajouter");
        jButton_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ajouterActionPerformed(evt);
            }
        });

        jLabel_Nom2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom2.setText("Score:");

        jComboBox_id_cours.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox_id_cours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Prénom", "sex", "DateNaissance", "Téléphone", "Adresse"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel_Nom3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom3.setText("Description:");

        jTextField_description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_descriptionActionPerformed(evt);
            }
        });
        jTextField_description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_descriptionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Nom)
                            .addComponent(jLabel_Nom1)
                            .addComponent(jLabel_Nom2)
                            .addComponent(jLabel_Nom3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_score)
                                .addComponent(jTextField_idetd)
                                .addComponent(jComboBox_id_cours, 0, 181, Short.MAX_VALUE))
                            .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Annuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_ajouter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Nom1)
                                    .addComponent(jTextField_idetd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Nom)
                                    .addComponent(jComboBox_id_cours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(jTextField_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Nom2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Nom3))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idetdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idetdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idetdActionPerformed

    private void jButton_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnnulerActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_jButton_AnnulerActionPerformed

    private void jButton_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ajouterActionPerformed
    
        Score sc=new Score();
        int etdid=Integer.valueOf(jTextField_idetd.getText());
        int coursid= c.getCoursId(jComboBox_id_cours.getSelectedItem().toString());
        float score=Float.valueOf(jTextField_score.getText());
        
        sc.insererAjouterSupp('a',etdid, coursid, score, jTextField_description.getText());
         try{ GestScores.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id_Etudiant","Id_Cours","Score","Description"}));
        sc.chargerScores(GestScores.jTable1);}catch(Exception ex){
             System.out.println(ex.getMessage());
        }
        
        //System.out.println(coursid);
         

// TODO add your handling code here:

//        AjouterCours get=new AjouterCours();
//        get.setVisible(true);
//        get.pack();
//        get.setLocationRelativeTo(null);
//        get.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton_ajouterActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int indice=jTable1.getSelectedRow();
       jTextField_idetd.setText(model.getValueAt(indice, 0).toString());
//
//        
//        jTextField_nom.setText(model.getValueAt(indice, 1).toString());
//        jTextField_prenom.setText(model.getValueAt(indice, 2).toString());
//        if((model.getValueAt(indice, 3).toString()).equals("H")){
//            jRadioButton_femme.setSelected(false);
//            jRadioButton_homm.setSelected(true);
//
//        }
//        else{
//            jRadioButton_homm.setSelected(false);
//            jRadioButton_femme.setSelected(true);
//
//        }
//        try {
//            Date d=new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(indice, 4).toString());
//            jDateChooser1.setDate(d);
//        } catch (ParseException ex) {
//            Logger.getLogger(GestEtudiant.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//        jTextField_tel.setText(model.getValueAt(indice, 5).toString());
//        jTextArea_ad.setText(model.getValueAt(indice, 6).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int indice=jTable1.getSelectedRow();
       jTextField_idetd.setText(model.getValueAt(indice, 0).toString());
//        if(evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN){
//            jTextField_id.setText(model.getValueAt(indice, 0).toString());
//            jTextField_nom.setText(model.getValueAt(indice, 1).toString());
//            jTextField_prenom.setText(model.getValueAt(indice, 2).toString());
//            if((model.getValueAt(indice, 3).toString()).equals("H")){
//                jRadioButton_femme.setSelected(false);
//                jRadioButton_homm.setSelected(true);
//
//            }
//            else{
//                jRadioButton_homm.setSelected(false);
//                jRadioButton_femme.setSelected(true);
//
//            }
//            try {
//                Date d=new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(indice, 4).toString());
//                jDateChooser1.setDate(d);
//            } catch (ParseException ex) {
//                Logger.getLogger(GestEtudiant.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//            jTextField_tel.setText(model.getValueAt(indice, 5).toString());
//            jTextArea_ad.setText(model.getValueAt(indice, 6).toString());
//
//        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTextField_scoreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_scoreKeyTyped
        //if(!Character.isDigit(evt.getKeyChar())){
            //            evt.consume();
            char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c!='.'  ) {
                
                   // String ch=jTextField_score.getText();
                  
                       // System.out.println(ch.contains("."));
                getToolkit().beep();
                evt.consume(); 
                
            }else if(jTextField_score.getText().contains(".")&&c=='.')
                evt.consume(); 
                
            // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_scoreKeyTyped

    private void jTextField_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_scoreActionPerformed

    private void jTextField_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_descriptionActionPerformed

    private void jTextField_descriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_descriptionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_descriptionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterScore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Annuler;
    private javax.swing.JButton jButton_ajouter;
    private javax.swing.JComboBox<String> jComboBox_id_cours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Nom;
    private javax.swing.JLabel jLabel_Nom1;
    private javax.swing.JLabel jLabel_Nom2;
    private javax.swing.JLabel jLabel_Nom3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_description;
    private javax.swing.JTextField jTextField_idetd;
    private javax.swing.JTextField jTextField_score;
    // End of variables declaration//GEN-END:variables
}
