/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestetudiant;

import static gestetudiant.GestEtudiant.jTable1;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEIF
 */
public class GestCours extends javax.swing.JFrame {

    /**
     * Creates new form GestCours
     */
    Cours c=new Cours();
      DefaultTableModel model;      
    public GestCours() {
        initComponents();
        c.chargerCours(jTable1, "");
        model=(DefaultTableModel) jTable1.getModel();
         jTable1.setRowHeight(40);
 jTable1.setShowGrid(true);
 jTable1.setGridColor(Color.BLACK);
 jTable1.setSelectionBackground(Color.blue);
    }
     public void vider(){
        
        jTextField_id.setText("");
        jTextField_libelle.setText("");
        jSpinner1.setValue(0);
     
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_libelle = new javax.swing.JTextField();
        jLabel_Nom = new javax.swing.JLabel();
        jLabel_Prenom = new javax.swing.JLabel();
        jButton_ajouter = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jButton_editer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_Nom1 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel_Date1 = new javax.swing.JLabel();
        jTextField_recherche = new javax.swing.JTextField();
        jButton_supp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gérer les cours");

        jTextField_libelle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_libelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_libelleActionPerformed(evt);
            }
        });

        jLabel_Nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom.setText("Libelle:");

        jLabel_Prenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Prenom.setText("Nombre d'heurs:");

        jButton_ajouter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton_ajouter.setText("Ajouter");
        jButton_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ajouterActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));

        jButton_editer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_editer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        jButton_editer.setText("Editer");
        jButton_editer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editerActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Libelle", "Nombre d'heure"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel_Nom1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom1.setText("Id:");

        jTextField_id.setEditable(false);
        jTextField_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jLabel_Date1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Date1.setText("Entrer une valeur à rechercher:");

        jTextField_recherche.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_rechercheActionPerformed(evt);
            }
        });
        jTextField_recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_rechercheKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_rechercheKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_rechercheKeyTyped(evt);
            }
        });

        jButton_supp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_supp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/error.png"))); // NOI18N
        jButton_supp.setText("Supprimer");
        jButton_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_supp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_editer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jButton_ajouter))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Prenom)
                            .addComponent(jLabel_Nom)
                            .addComponent(jLabel_Nom1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Date1)
                    .addComponent(jTextField_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Nom1)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Nom)
                            .addComponent(jTextField_libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Prenom)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_editer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_libelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_libelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_libelleActionPerformed

    private void jButton_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ajouterActionPerformed
        // TODO add your handling code here:
      
      AjouterCours get=new AjouterCours();
        get.setVisible(true);
        get.pack();
        get.setLocationRelativeTo(null);
        get.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButton_ajouterActionPerformed
public boolean verifText(){
        if(jTextField_libelle.getText().equals("")||(Integer)jSpinner1.getValue()==0
                ){
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs S.V.P!");
            return false;}
        
       
        
    
        
        else
        return true;
    }
    private void jButton_editerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editerActionPerformed
        // TODO add your handling code here:
        Cours e=new Cours();
        String s="";
       
       
           if(verifText()){

            e.insererAjouterSupp('m',Integer.parseInt(jTextField_id.getText()), jTextField_libelle.getText(),(Integer)jSpinner1.getValue());
            jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Libelle","Nombre d'heure"}));
            e.chargerCours( jTable1, "");
            //MaFonction mf=new MaFonction();
            //Principale.jLabel_nbetd.setText("Nombre d'etudiants ="+mf.getNombreDonnees("etudiant"));
           }
    }//GEN-LAST:event_jButton_editerActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int indice;
        indice=jTable1.getSelectedRow();

        jTextField_id.setText(model.getValueAt(indice, 0).toString());
        jTextField_libelle.setText(model.getValueAt(indice, 1).toString());
       jSpinner1.setValue(Integer.valueOf(model.getValueAt(indice, 2).toString()));
        

        
        

        

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
       int indice;
        indice=jTable1.getSelectedRow();
        if(evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN){
            jTextField_id.setText(model.getValueAt(indice, 0).toString());
            jTextField_libelle.setText(model.getValueAt(indice, 1).toString());
           jSpinner1.setValue(Integer.valueOf(model.getValueAt(indice, 2).toString()));
            
            

            
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jTextField_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_rechercheActionPerformed

    private void jTextField_rechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_rechercheKeyPressed

    }//GEN-LAST:event_jTextField_rechercheKeyPressed

    private void jTextField_rechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_rechercheKeyReleased
        // TODO add your handling code here:
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Libelle","Nombre d'heurs"}));

        c.chargerCours(jTable1, jTextField_recherche.getText());
    }//GEN-LAST:event_jTextField_rechercheKeyReleased

    private void jTextField_rechercheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_rechercheKeyTyped

    }//GEN-LAST:event_jTextField_rechercheKeyTyped

    private void jButton_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suppActionPerformed
        // TODO add your handling code here:
        if(jTextField_id.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selectionner un cours S.V.P!");

        }else{
            Cours e=new Cours();
            e.insererAjouterSupp('s', Integer.parseInt(jTextField_id.getText()), null, null);
            MaFonction mf=new MaFonction();
            Principale.jLabel_nbcours.setText("Nombre du cours ="+mf.getNombreDonnees("cours"));
            vider();
            jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Libelle","Nombre d'heurs"}));
            c.chargerCours( jTable1, "");}
    }//GEN-LAST:event_jButton_suppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestCours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestCours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ajouter;
    private javax.swing.JButton jButton_editer;
    private javax.swing.JButton jButton_supp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Date1;
    private javax.swing.JLabel jLabel_Nom;
    private javax.swing.JLabel jLabel_Nom1;
    private javax.swing.JLabel jLabel_Prenom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_libelle;
    private javax.swing.JTextField jTextField_recherche;
    // End of variables declaration//GEN-END:variables
}
