/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestetudiant;

import static gestetudiant.GestCours.jTable1;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEIF
 */
public class GestScores extends javax.swing.JFrame {

    /**
     * Creates new form GestScores
     */
    Score sc=new Score();
    public GestScores() {
        initComponents();
        sc.chargerScores(jTable1);
        jTable1.setRowHeight(40);
 jTable1.setShowGrid(true);
 jTable1.setGridColor(Color.BLACK);
 jTable1.setSelectionBackground(Color.blue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_idetd = new javax.swing.JTextField();
        jLabel_Nom1 = new javax.swing.JLabel();
        jLabel_Nom = new javax.swing.JLabel();
        jTextField_score = new javax.swing.JTextField();
        jButton_supprimer = new javax.swing.JButton();
        jButton_editer = new javax.swing.JButton();
        jLabel_Nom2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_Nom3 = new javax.swing.JLabel();
        jTextField_description = new javax.swing.JTextField();
        jTextField_idCours = new javax.swing.JTextField();
        jButton_ajouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gérer les scores");

        jTextField_idetd.setEditable(false);
        jTextField_idetd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_idetd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idetdActionPerformed(evt);
            }
        });

        jLabel_Nom1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom1.setText("Id Etudiant:");

        jLabel_Nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom.setText("Id Cours:");

        jTextField_score.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_scoreActionPerformed(evt);
            }
        });
        jTextField_score.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_scoreKeyTyped(evt);
            }
        });

        jButton_supprimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/error.png"))); // NOI18N
        jButton_supprimer.setText("Supprimer");
        jButton_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_supprimerActionPerformed(evt);
            }
        });

        jButton_editer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_editer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        jButton_editer.setText("Editer");
        jButton_editer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editerActionPerformed(evt);
            }
        });

        jLabel_Nom2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom2.setText("Score:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Etudiant", "Id_Cours", "Score", "Description"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel_Nom3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom3.setText("Description:");

        jTextField_description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_descriptionActionPerformed(evt);
            }
        });
        jTextField_description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_descriptionKeyTyped(evt);
            }
        });

        jTextField_idCours.setEditable(false);
        jTextField_idCours.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_idCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idCoursActionPerformed(evt);
            }
        });

        jButton_ajouter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton_ajouter.setText("Ajouter");
        jButton_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ajouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_Nom)
                                    .addComponent(jLabel_Nom1)
                                    .addComponent(jLabel_Nom2)
                                    .addComponent(jLabel_Nom3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_score, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                        .addComponent(jTextField_idetd)
                                        .addComponent(jTextField_idCours))
                                    .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton_supprimer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_editer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Nom1)
                                    .addComponent(jTextField_idetd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_Nom)
                                    .addComponent(jTextField_idCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(jTextField_score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Nom2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Nom3))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_editer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idetdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idetdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idetdActionPerformed

    private void jTextField_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_scoreActionPerformed

    private void jTextField_scoreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_scoreKeyTyped
        //if(!Character.isDigit(evt.getKeyChar())){
            //            evt.consume();
            char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c!='.'  ) {

                // String ch=jTextField_score.getText();

                // System.out.println(ch.contains("."));
                getToolkit().beep();
                evt.consume();

            }else if(jTextField_score.getText().contains(".")&&c=='.')
            evt.consume();

            // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_scoreKeyTyped
public void vider(){
        
        jTextField_idetd.setText("");
        jTextField_idCours.setText("");
        jTextField_score.setText("");
        jTextField_description.setText("");

}
    private void jButton_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_supprimerActionPerformed
        // TODO add your handling code here:
        
        if(jTextField_idetd.getText().equals("")||jTextField_idCours.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Selectionner une ligne a supprimer  S.V.P!");

        }else{
            
          
            Score e=new Score();
            e.insererAjouterSupp('s', Integer.parseInt(jTextField_idetd.getText()),Integer.parseInt(jTextField_idCours.getText()), null, null);
          //  MaFonction mf=new MaFonction();
           // Principale.jLabel_nbcours.setText("Nombre du cours ="+mf.getNombreDonnees("cours"));
            vider();
            jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id_Etudiant","Id_Cours","Score","Description"}));
            e.chargerScores(jTable1);}
        
                  
    }//GEN-LAST:event_jButton_supprimerActionPerformed
public boolean verifText(){
        if(jTextField_idetd.getText().equals("")||jTextField_idCours.getText().equals("")||jTextField_score.getText().equals("")||
                jTextField_description.getText().equals("")     ){
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs S.V.P!");
            return false;}
return true;}
    private void jButton_editerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editerActionPerformed

 Score e=new Score();
        
       
       
           if(verifText()){

            e.insererAjouterSupp('m',Integer.parseInt(jTextField_idetd.getText()), Integer.valueOf(jTextField_idCours.getText()),Float.valueOf(jTextField_score.getText()),jTextField_description.getText());
            jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id_Etudiant","Id_Cours","Score","Description"}));
            e.chargerScores(jTable1);
    }//GEN-LAST:event_jButton_editerActionPerformed
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int indice=jTable1.getSelectedRow();
        jTextField_idetd.setText(model.getValueAt(indice, 0).toString());
        jTextField_idCours.setText(model.getValueAt(indice, 1).toString());
        jTextField_score.setText(model.getValueAt(indice, 2).toString());
        jTextField_description.setText(model.getValueAt(indice, 3).toString());
              
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
         DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int indice=jTable1.getSelectedRow();
        jTextField_idetd.setText(model.getValueAt(indice, 0).toString());
        jTextField_idCours.setText(model.getValueAt(indice, 1).toString());
        jTextField_score.setText(model.getValueAt(indice, 2).toString());
        jTextField_description.setText(model.getValueAt(indice, 3).toString());
       
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTextField_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_descriptionActionPerformed

    private void jTextField_descriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_descriptionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_descriptionKeyTyped

    private void jTextField_idCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idCoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idCoursActionPerformed

    private void jButton_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ajouterActionPerformed

 AjouterScore get=new AjouterScore();
        get.setVisible(true);
        get.pack();
        get.setLocationRelativeTo(null);
        get.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton_ajouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestScores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ajouter;
    private javax.swing.JButton jButton_editer;
    private javax.swing.JButton jButton_supprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Nom;
    private javax.swing.JLabel jLabel_Nom1;
    private javax.swing.JLabel jLabel_Nom2;
    private javax.swing.JLabel jLabel_Nom3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_description;
    private javax.swing.JTextField jTextField_idCours;
    private javax.swing.JTextField jTextField_idetd;
    private javax.swing.JTextField jTextField_score;
    // End of variables declaration//GEN-END:variables
}
