/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestetudiant;

import static gestetudiant.GestCours.jTable1;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEIF
 */
public class GestEtudiant extends javax.swing.JFrame {

    /**
     * Creates new form GestEtudiant
     */
    Etudiant et=new Etudiant();
     DefaultTableModel model;
    public GestEtudiant() {
        initComponents();
        et.chargerEtudiants(jTable1, "");
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton_homm);
        bg.add(jRadioButton_femme);
   jRadioButton_homm.setSelected(true);
 model=(DefaultTableModel) jTable1.getModel();
 jTable1.setRowHeight(50);
 jTable1.setShowGrid(true);
 jTable1.setGridColor(Color.black);
 jTable1.setSelectionBackground(Color.blue);
    }
    public void vider(){
        jTextArea_ad.setText("");
        jTextField_id.setText("");
        jTextField_nom.setText("");
        jTextField_prenom.setText("");
        jTextField_tel.setText("");
        Date d=null;
        
        
        jRadioButton_homm.setSelected(true);
        jRadioButton_femme.setSelected(false);
        jDateChooser1.setDate(d);
       
    }
    public boolean verifText(){
        if(jTextArea_ad.getText().equals("")||jTextField_nom.getText().equals("")||jTextField_prenom.getText().equals("")
                ||jTextField_tel.getText().equals("")||jDateChooser1.getDate()==null||jTextField_id.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs S.V.P!");
            return false;}
        
        else if(jDateChooser1.getDate().compareTo(new Date() )> 0){
            JOptionPane.showMessageDialog(null, "Aucun étudiant du futur n'est autorisé!");
            return false;
        
    }
        
        else
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Nom = new javax.swing.JLabel();
        jLabel_Prenom = new javax.swing.JLabel();
        jLabel_sex = new javax.swing.JLabel();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_tel = new javax.swing.JLabel();
        jLabel_adresse = new javax.swing.JLabel();
        jTextField_nom = new javax.swing.JTextField();
        jTextField_prenom = new javax.swing.JTextField();
        jTextField_tel = new javax.swing.JTextField();
        jRadioButton_homm = new javax.swing.JRadioButton();
        jRadioButton_femme = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_ad = new javax.swing.JTextArea();
        jButton_editer = new javax.swing.JButton();
        jButton_supp = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel_id = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jButton_ajouter1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_recherche = new javax.swing.JTextField();
        jLabel_Date1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Gérer les étudiants");

        jLabel_Nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom.setText("Nom:");

        jLabel_Prenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Prenom.setText("Prenom:");

        jLabel_sex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_sex.setText("Sex:");

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Date.setText("Date de naissance:");

        jLabel_tel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_tel.setText("Telephone:");

        jLabel_adresse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_adresse.setText("Adresse:");

        jTextField_nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nomActionPerformed(evt);
            }
        });

        jTextField_prenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_prenomActionPerformed(evt);
            }
        });

        jTextField_tel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telActionPerformed(evt);
            }
        });
        jTextField_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_telKeyTyped(evt);
            }
        });

        jRadioButton_homm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_homm.setText("Homme");

        jRadioButton_femme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_femme.setText("Femme");

        jTextArea_ad.setColumns(20);
        jTextArea_ad.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea_ad.setRows(5);
        jScrollPane1.setViewportView(jTextArea_ad);

        jButton_editer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_editer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        jButton_editer.setText("Editer");
        jButton_editer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editerActionPerformed(evt);
            }
        });

        jButton_supp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_supp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/error.png"))); // NOI18N
        jButton_supp.setText("Supprimer");
        jButton_supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_suppActionPerformed(evt);
            }
        });

        jLabel_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_id.setText("Id:");

        jTextField_id.setEditable(false);
        jTextField_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });
        jTextField_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_idKeyTyped(evt);
            }
        });

        jButton_ajouter1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ajouter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton_ajouter1.setText("Ajouter");
        jButton_ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ajouter1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nom", "Prénom", "sex", "DateNaissance", "Téléphone", "Adresse"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTextField_recherche.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_rechercheActionPerformed(evt);
            }
        });
        jTextField_recherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_rechercheKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_rechercheKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_rechercheKeyTyped(evt);
            }
        });

        jLabel_Date1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Date1.setText("Entrer une valeur à rechercher:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_id)
                            .addComponent(jLabel_sex)
                            .addComponent(jLabel_Date)
                            .addComponent(jLabel_Prenom)
                            .addComponent(jLabel_Nom)
                            .addComponent(jLabel_tel)
                            .addComponent(jLabel_adresse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jRadioButton_homm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(jRadioButton_femme, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addComponent(jScrollPane1)
                            .addComponent(jTextField_tel)
                            .addComponent(jTextField_prenom)
                            .addComponent(jTextField_nom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButton_supp)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_editer)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ajouter1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Date1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(324, 324, 324))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_id)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nom)
                    .addComponent(jTextField_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Prenom))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_sex)
                    .addComponent(jRadioButton_homm)
                    .addComponent(jRadioButton_femme))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Date)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tel)
                    .addComponent(jTextField_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_adresse))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_editer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_supp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Date1)
                    .addComponent(jTextField_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nomActionPerformed

    private void jTextField_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_prenomActionPerformed

    private void jTextField_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telActionPerformed

    private void jTextField_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();

        }
    }//GEN-LAST:event_jTextField_telKeyTyped

    private void jButton_editerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editerActionPerformed
        // TODO add your handling code here:
        Etudiant e=new Etudiant();
        String s="";
        if(jRadioButton_homm.isSelected())
        s="H";
        else
        s="F";
        if(verifText()){
            SimpleDateFormat date=new SimpleDateFormat("YYYY-MM-dd");
            String datenai=date.format(jDateChooser1.getDate());
            System.out.print(datenai);

            e.insererAjouterSupp('m',Integer.parseInt(jTextField_id.getText()), jTextField_nom.getText(),jTextField_prenom.getText() ,s, datenai,jTextField_tel.getText(), jTextArea_ad.getText());
         jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Nom","Prénom","Sex","DateNaissance","Téléphone","Adresse"}));
        et.chargerEtudiants( jTable1, "");  
//MaFonction mf=new MaFonction();
            //Principale.jLabel_nbetd.setText("Nombre d'etudiants ="+mf.getNombreDonnees("etudiant"));
        }

    }//GEN-LAST:event_jButton_editerActionPerformed

    private void jButton_suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_suppActionPerformed
                // TODO add your handling code here:
                if(jTextField_id.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Selectionner un etudiant S.V.P!");
                    
                }else{
                 Etudiant e=new Etudiant();
                 e.insererAjouterSupp('s', Integer.parseInt(jTextField_id.getText()), null, null, null, null, null, null);
                 MaFonction mf=new MaFonction();
        Principale.jLabel_nbetd.setText("Nombre d'etudiants ="+mf.getNombreDonnees("etudiant"));
                 vider();
                 jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Nom","Prénom","Sex","DateNaissance","Téléphone","Adresse"}));
        et.chargerEtudiants( jTable1, "");}  
    }//GEN-LAST:event_jButton_suppActionPerformed

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jButton_ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ajouter1ActionPerformed
        NouveauEtudiant get=new NouveauEtudiant();
        get.setVisible(true);
        get.pack();
        get.setLocationRelativeTo(null);
        get.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton_ajouter1ActionPerformed
 
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int indice;
        indice=jTable1.getSelectedRow();
       
       jTextField_id.setText(model.getValueAt(indice, 0).toString());
        jTextField_nom.setText(model.getValueAt(indice, 1).toString());
        jTextField_prenom.setText(model.getValueAt(indice, 2).toString());
        if((model.getValueAt(indice, 3).toString()).equals("H")){
            jRadioButton_femme.setSelected(false);
            jRadioButton_homm.setSelected(true);
            
        } 
        else{
            jRadioButton_homm.setSelected(false);
             jRadioButton_femme.setSelected(true);
             
        }
        try {
            Date d=new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(indice, 4).toString());
            jDateChooser1.setDate(d);
        } catch (ParseException ex) {
            Logger.getLogger(GestEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                jTextField_tel.setText(model.getValueAt(indice, 5).toString());
                jTextArea_ad.setText(model.getValueAt(indice, 6).toString());
         
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_rechercheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_rechercheActionPerformed

    private void jTextField_rechercheKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_rechercheKeyTyped
      
    }//GEN-LAST:event_jTextField_rechercheKeyTyped

    private void jTextField_rechercheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_rechercheKeyPressed
      
    }//GEN-LAST:event_jTextField_rechercheKeyPressed

    private void jTextField_rechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_rechercheKeyReleased
        // TODO add your handling code here:
         jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Nom","Prénom","Sex","DateNaissance","Téléphone","Adresse"}));
        
        et.chargerEtudiants(jTable1, jTextField_recherche.getText());
    }//GEN-LAST:event_jTextField_rechercheKeyReleased

    private void jTextField_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idKeyTyped
       if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();}
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idKeyTyped

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
       int indice;
        indice=jTable1.getSelectedRow();
        if(evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN){
        jTextField_id.setText(model.getValueAt(indice, 0).toString());
        jTextField_nom.setText(model.getValueAt(indice, 1).toString());
        jTextField_prenom.setText(model.getValueAt(indice, 2).toString());
        if((model.getValueAt(indice, 3).toString()).equals("H")){
            jRadioButton_femme.setSelected(false);
            jRadioButton_homm.setSelected(true);
            
        } 
        else{
            jRadioButton_homm.setSelected(false);
             jRadioButton_femme.setSelected(true);
             
        }
        try {
            Date d=new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(indice, 4).toString());
            jDateChooser1.setDate(d);
        } catch (ParseException ex) {
            Logger.getLogger(GestEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                jTextField_tel.setText(model.getValueAt(indice, 5).toString());
                jTextArea_ad.setText(model.getValueAt(indice, 6).toString());
            
       }
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestEtudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ajouter1;
    private javax.swing.JButton jButton_editer;
    private javax.swing.JButton jButton_supp;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Date1;
    private javax.swing.JLabel jLabel_Nom;
    private javax.swing.JLabel jLabel_Prenom;
    private javax.swing.JLabel jLabel_adresse;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_sex;
    private javax.swing.JLabel jLabel_tel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_femme;
    private javax.swing.JRadioButton jRadioButton_homm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_ad;
    public javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_nom;
    private javax.swing.JTextField jTextField_prenom;
    private javax.swing.JTextField jTextField_recherche;
    private javax.swing.JTextField jTextField_tel;
    // End of variables declaration//GEN-END:variables
}
