/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestetudiant;

import static gestetudiant.GestEtudiant.jTable1;
import java.text.SimpleDateFormat;
import java.util.Date;
import javafx.scene.control.Tooltip;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SEIF
 */
public class NouveauEtudiant extends javax.swing.JFrame {

    /**
     * Creates new form NouveauEtudiant
     */
   Etudiant et = new Etudiant();
    public NouveauEtudiant() {
        initComponents();
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButton_homm);
        bg.add(jRadioButton_femme);
   jRadioButton_homm.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Nom = new javax.swing.JLabel();
        jLabel_Prenom = new javax.swing.JLabel();
        jLabel_sex = new javax.swing.JLabel();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_tel = new javax.swing.JLabel();
        jLabel_adresse = new javax.swing.JLabel();
        jTextField_nom = new javax.swing.JTextField();
        jTextField_prenom = new javax.swing.JTextField();
        jTextField_tel = new javax.swing.JTextField();
        jRadioButton_homm = new javax.swing.JRadioButton();
        jRadioButton_femme = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_ad = new javax.swing.JTextArea();
        jButton_ajouter = new javax.swing.JButton();
        jButton_annuler = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Nouveau etudiant");

        jLabel_Nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Nom.setText("Nom:");

        jLabel_Prenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Prenom.setText("Prenom:");

        jLabel_sex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_sex.setText("Sex:");

        jLabel_Date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Date.setText("Date de naissance:");

        jLabel_tel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_tel.setText("Telephone:");

        jLabel_adresse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_adresse.setText("Adresse:");

        jTextField_nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nomActionPerformed(evt);
            }
        });

        jTextField_prenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_prenomActionPerformed(evt);
            }
        });

        jTextField_tel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telActionPerformed(evt);
            }
        });
        jTextField_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_telKeyTyped(evt);
            }
        });

        jRadioButton_homm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_homm.setText("Homme");

        jRadioButton_femme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton_femme.setText("Femme");

        jTextArea_ad.setColumns(20);
        jTextArea_ad.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea_ad.setRows(5);
        jScrollPane1.setViewportView(jTextArea_ad);

        jButton_ajouter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton_ajouter.setText("Ajouter");
        jButton_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ajouterActionPerformed(evt);
            }
        });

        jButton_annuler.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/error.png"))); // NOI18N
        jButton_annuler.setText("Annuler");
        jButton_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_annuler)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ajouter))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_sex)
                                    .addComponent(jLabel_Date)
                                    .addComponent(jLabel_Prenom)
                                    .addComponent(jLabel_Nom)
                                    .addComponent(jLabel_tel)
                                    .addComponent(jLabel_adresse))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButton_homm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                        .addComponent(jRadioButton_femme, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19))
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTextField_tel)
                                    .addComponent(jTextField_prenom)
                                    .addComponent(jTextField_nom, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nom)
                    .addComponent(jTextField_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Prenom))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_sex)
                    .addComponent(jRadioButton_homm)
                    .addComponent(jRadioButton_femme))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Date)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_tel)
                    .addComponent(jTextField_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_adresse))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nomActionPerformed

    private void jTextField_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_prenomActionPerformed

    private void jTextField_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telActionPerformed

    private void jButton_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_annulerActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_annulerActionPerformed

    private void jTextField_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
           
        }
    }//GEN-LAST:event_jTextField_telKeyTyped

    public boolean verifText(){
        if(jTextArea_ad.getText().equals("")||jTextField_nom.getText().equals("")||jTextField_prenom.getText().equals("")
                ||jTextField_tel.getText().equals("")||jDateChooser1.getDate()==null){
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs S.V.P!");
            return false;}
        
        else if(jDateChooser1.getDate().compareTo(new Date() )> 0){
            JOptionPane.showMessageDialog(null, "Aucun étudiant du futur n'est autorisé!");
            return false;
        
    }
        
        else
        return true;
    }
    
    private void jButton_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ajouterActionPerformed
        // TODO add your handling code here:
        Etudiant e=new Etudiant();
        String s="";
        if(jRadioButton_homm.isSelected())
            s="H";
        else
            s="F";
        if(verifText()){
             SimpleDateFormat date=new SimpleDateFormat("YYYY-MM-dd");
        String datenai=date.format(jDateChooser1.getDate());
        System.out.print(datenai);
        
        e.insererAjouterSupp('a',1, jTextField_nom.getText(),jTextField_prenom.getText() ,s, datenai,jTextField_tel.getText(), jTextArea_ad.getText());
        MaFonction mf=new MaFonction();
        Principale.jLabel_nbetd.setText("Nombre d'etudiants ="+mf.getNombreDonnees("etudiant"));
        }
        try{
            GestEtudiant.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id","Nom","Prénom","Sex","DateNaissance","Téléphone","Adresse"}));
        et.chargerEtudiants( GestEtudiant.jTable1, "");
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
         
        vider();
      
    }//GEN-LAST:event_jButton_ajouterActionPerformed
public void vider(){
        jTextArea_ad.setText("");
       
        jTextField_nom.setText("");
        jTextField_prenom.setText("");
        jTextField_tel.setText("");
        Date d=null;
        
        
        jRadioButton_homm.setSelected(true);
        jRadioButton_femme.setSelected(false);
        jDateChooser1.setDate(d);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NouveauEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NouveauEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NouveauEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NouveauEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NouveauEtudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ajouter;
    private javax.swing.JButton jButton_annuler;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Nom;
    private javax.swing.JLabel jLabel_Prenom;
    private javax.swing.JLabel jLabel_adresse;
    private javax.swing.JLabel jLabel_sex;
    private javax.swing.JLabel jLabel_tel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_femme;
    private javax.swing.JRadioButton jRadioButton_homm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_ad;
    private javax.swing.JTextField jTextField_nom;
    private javax.swing.JTextField jTextField_prenom;
    private javax.swing.JTextField jTextField_tel;
    // End of variables declaration//GEN-END:variables
}
