/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestetudiant;

import javax.swing.JFrame;

/**
 *
 * @author SEIF
 */
public class Principale extends javax.swing.JFrame {

    /**
     * Creates new form Principale
     */
    public Principale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Bienvenue = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_nbetd = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_nbcours = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem_gerer = new javax.swing.JMenuItem();
        jMenu_cour = new javax.swing.JMenu();
        jMenuItem_ajoutCours = new javax.swing.JMenuItem();
        jMenuItem_gererCours = new javax.swing.JMenuItem();
        jMenu_scores = new javax.swing.JMenu();
        jMenuItem_ajouterScores = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Bienvenue.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel_Bienvenue.setText("Bienvenue<****>");

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel_nbetd.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel_nbetd.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nbetd.setText("Nombre d'etudiants=");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_nbetd, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel_nbetd)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jLabel_nbcours.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel_nbcours.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nbcours.setText("Nombre de coours=");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_nbcours, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel_nbcours)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/school.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jLabel_Bienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(328, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Bienvenue))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/presentation.png"))); // NOI18N
        jMenu4.setText("Etudiants");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        jMenuItem1.setText("Ajouter");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem_gerer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/network.png"))); // NOI18N
        jMenuItem_gerer.setText("Gérer");
        jMenuItem_gerer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gererActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_gerer);

        jMenuBar1.add(jMenu4);

        jMenu_cour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/open-magazine.png"))); // NOI18N
        jMenu_cour.setText("Cours");

        jMenuItem_ajoutCours.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/addcour.png"))); // NOI18N
        jMenuItem_ajoutCours.setText("Ajouter");
        jMenuItem_ajoutCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ajoutCoursActionPerformed(evt);
            }
        });
        jMenu_cour.add(jMenuItem_ajoutCours);

        jMenuItem_gererCours.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/folder.png"))); // NOI18N
        jMenuItem_gererCours.setText("Gérer");
        jMenuItem_gererCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gererCoursActionPerformed(evt);
            }
        });
        jMenu_cour.add(jMenuItem_gererCours);

        jMenuBar1.add(jMenu_cour);

        jMenu_scores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/scoreboard.png"))); // NOI18N
        jMenu_scores.setText("Scores");

        jMenuItem_ajouterScores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        jMenuItem_ajouterScores.setText("Ajouter");
        jMenuItem_ajouterScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ajouterScoresActionPerformed(evt);
            }
        });
        jMenu_scores.add(jMenuItem_ajouterScores);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/organize.png"))); // NOI18N
        jMenuItem2.setText("Gérer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu_scores.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calendar.png"))); // NOI18N
        jMenuItem3.setText("Tous les scores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu_scores.add(jMenuItem3);

        jMenuBar1.add(jMenu_scores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         NouveauEtudiant p=new NouveauEtudiant();
                   p.setVisible(true);
                   p.pack();
                   p.setLocationRelativeTo(null);
                   p.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem_gererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gererActionPerformed
        GestEtudiant get=new GestEtudiant();
        get.setVisible(true);
        get.pack();
        get.setLocationRelativeTo(null);
        get.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem_gererActionPerformed

    private void jMenuItem_ajoutCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ajoutCoursActionPerformed
        AjouterCours get=new AjouterCours();
        get.setVisible(true);
        get.pack();
        get.setLocationRelativeTo(null);
        get.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem_ajoutCoursActionPerformed

    private void jMenuItem_gererCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gererCoursActionPerformed
 GestCours get=new GestCours();
        get.setVisible(true);
        get.pack();
        get.setLocationRelativeTo(null);
        get.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);       
    }//GEN-LAST:event_jMenuItem_gererCoursActionPerformed

    private void jMenuItem_ajouterScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ajouterScoresActionPerformed
        // TODO add your handling code here:
        AjouterScore get=new AjouterScore();
        get.setVisible(true);
        get.pack();
        get.setLocationRelativeTo(null);
        get.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
    }//GEN-LAST:event_jMenuItem_ajouterScoresActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          GestScores get=new GestScores();
        get.setVisible(true);
        get.pack();
        get.setLocationRelativeTo(null);
        get.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         TousLesScores get=new TousLesScores();
        get.setVisible(true);
        get.pack();
        get.setLocationRelativeTo(null);
        get.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel_Bienvenue;
    public static javax.swing.JLabel jLabel_nbcours;
    public static javax.swing.JLabel jLabel_nbetd;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem_ajoutCours;
    private javax.swing.JMenuItem jMenuItem_ajouterScores;
    private javax.swing.JMenuItem jMenuItem_gerer;
    private javax.swing.JMenuItem jMenuItem_gererCours;
    private javax.swing.JMenu jMenu_cour;
    private javax.swing.JMenu jMenu_scores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
